export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const SET_CURRENT_SKILL = 'SET_CURRENT_SKILL';
export const GET_ENTRY_SUCCESS = 'GET_ENTRY_SUCCESS';
export const GET_BLURB_SUCCESS = 'GET_BLURB_SUCCESS';
export const SET_MENU_STATE = 'SET_MENU_STATE';
export const INCREASE_RANGE = 'INCREASE_RANGE';
export const CLOSE_MENU = 'CLOSE_MENU';
